CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(160) NOT NULL,
  sku varchar(80) NOT NULL UNIQUE,
  price numeric(12,2) NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'active',
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullName" varchar(180) NOT NULL,
  email varchar(180) NOT NULL UNIQUE,
  phone varchar(40),
  status varchar(40) NOT NULL DEFAULT 'active',
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" integer NOT NULL,
  quantity integer NOT NULL,
  "reservedQuantity" integer NOT NULL DEFAULT 0,
  "warehouseCode" varchar(80) NOT NULL,
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" integer NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'created',
  "totalAmount" numeric(12,2) NOT NULL,
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  "productId" integer NOT NULL,
  quantity integer NOT NULL,
  "unitPrice" numeric(12,2) NOT NULL,
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" integer NOT NULL,
  amount numeric(12,2) NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'pending',
  provider varchar(80) NOT NULL,
  "transactionRef" varchar(160),
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

